# ==========================================
# CrocoCamp Configuration Example with Obs Types
# ==========================================
#
# This example shows how to configure observation types for DART assimilation
# using CrocoCamp's new obs_types functionality.

# Required: Path to DART's perfect model obs executable
perfect_model_obs_dir: /path/to/DART/models/MOM6/work

# Required: Input directory containing model .nc files to process  
model_files_folder: /path/to/model/files/

# Required: Model configuration files (must be .nc files)
template_file: /path/to/model/files/template.nc
static_file: /path/to/model/files/mom6.h.static.nc
ocean_geometry: /path/to/model/files/mom6.h.ocean_geometry.nc

# Required: Directory containing observation files (obs_seq.in format)
obs_seq_in_folder: /path/to/obs_seq_files/

# Required: Output directories (will be created if they don't exist)
output_folder: /path/to/output/
input_nml_bck: /path/to/backups/
trimmed_obs_folder: /path/to/trimmed_obs/
parquet_folder: /path/to/parquet_output/

# ==========================================
# NEW FEATURE: Observation Types Configuration
# ==========================================
# 
# This section configures which observation types will be assimilated by DART.
# The obs_types are automatically validated against DART's obs_def_ocean_mod.rst
# and the input.nml file is updated with proper Fortran formatting.

use_these_obs:
  # Specific observation types - these must exactly match DART definitions
  - FLOAT_TEMPERATURE          # Argo float temperature measurements
  - FLOAT_SALINITY            # Argo float salinity measurements
  - CTD_TEMPERATURE           # CTD temperature profiles
  - CTD_SALINITY             # CTD salinity profiles

  # ALL_<FIELD> syntax - expands to all observation types for that quantity
  - ALL_TEMPERATURE           # Includes ALL temperature types:
                              #   ARGO_TEMPERATURE, BOTTLE_TEMPERATURE, 
                              #   SATELLITE_MICROWAVE_SST, XBT_TEMPERATURE,
                              #   GLIDER_TEMPERATURE, MOORING_TEMPERATURE, etc.
  
  # You can mix specific types with ALL_ expansions
  - SATELLITE_SSH             # Sea surface height from satellites
  # - ALL_SALINITY            # Uncomment to include all salinity types
  # - ALL_U_CURRENT_COMPONENT # Uncomment for all U-velocity observations
  # - ALL_V_CURRENT_COMPONENT # Uncomment for all V-velocity observations

# Alternative minimal configuration - just temperatures and salinities:
# use_these_obs:
#   - ALL_TEMPERATURE
#   - ALL_SALINITY

# Alternative comprehensive configuration - all supported types:  
# use_these_obs:
#   - ALL_TEMPERATURE
#   - ALL_SALINITY
#   - ALL_U_CURRENT_COMPONENT
#   - ALL_V_CURRENT_COMPONENT
#   - ALL_SEA_SURFACE_HEIGHT

# ==========================================
# Time Window Configuration
# ==========================================
# Time window for matching observations to model output
time_window:
  days: 5      # Primary time window in days
  hours: 0     # Additional hours
  minutes: 0   # Additional minutes  
  seconds: 0   # Additional seconds
  weeks: 0     # Additional weeks (converted to days)
  months: 0    # Additional months (converted to days, ~30 days/month)
  years: 0     # Additional years (converted to days, ~365 days/year)

# ==========================================
# Notes on Observation Types
# ==========================================
#
# Supported ALL_<FIELD> expansions (based on DART's obs_def_ocean_mod.rst):
#
# - ALL_TEMPERATURE: Expands to ~21 temperature observation types including:
#   TEMPERATURE, ARGO_TEMPERATURE, FLOAT_TEMPERATURE, CTD_TEMPERATURE,
#   XBT_TEMPERATURE, SATELLITE_MICROWAVE_SST, BOTTLE_TEMPERATURE, etc.
#
# - ALL_SALINITY: Expands to ~17 salinity observation types including:
#   SALINITY, ARGO_SALINITY, FLOAT_SALINITY, CTD_SALINITY, 
#   BOTTLE_SALINITY, GLIDER_SALINITY, etc.
#
# - ALL_U_CURRENT_COMPONENT: Expands to ~8 U-velocity observation types
# - ALL_V_CURRENT_COMPONENT: Expands to ~8 V-velocity observation types  
# - ALL_SEA_SURFACE_HEIGHT: Expands to sea surface height types
# - ALL_SEA_SURFACE_PRESSURE: Expands to pressure observation types
# - ALL_SEA_SURFACE_ANOMALY: Expands to anomaly observation types
#
# The complete list depends on your DART installation's obs_def_ocean_mod.rst file.
# Invalid observation types will cause a warning but won't stop the workflow.

# ==========================================
# Error Handling
# ==========================================
#
# If obs_def_ocean_mod.rst cannot be found or parsed:
# - A warning is displayed
# - The workflow continues with the existing input.nml configuration
# - No changes are made to the obs_kind_nml section
#
# If invalid observation types are specified:
# - Clear error messages identify the problematic types
# - Suggestions are provided for valid alternatives
# - The workflow stops to prevent incorrect assimilation setup