# ==========================================
# CrocoCamp Configuration Example
# ==========================================

# Required: Path to DART's perfect model obs executable
perfect_model_obs_dir: /path/to/DART/models/MOM6/work

# Required: Input directory containing model .nc files to process  
model_files_folder: /path/to/model/files/

# Required: Model configuration files (must be .nc files)
template_file: /path/to/model/files/template.nc
static_file: /path/to/model/files/mom6.h.static.nc
ocean_geometry: /path/to/model/files/mom6.h.ocean_geometry.nc

# Required: Directory containing observation files (obs_seq.in format)
obs_seq_in_folder: /path/to/obs_seq_files/

# Required: Output directories (will be created if they don't exist)
output_folder: /path/to/output/
input_nml_bck: /path/to/backups/
trimmed_obs_folder: /path/to/trimmed_obs/
parquet_folder: /path/to/parquet_output/

# Observation types to assimilate (can include ALL_<FIELD> entries)
use_these_obs:
  - FLOAT_TEMPERATURE          # Argo float temperature measurements
  - FLOAT_SALINITY            # Argo float salinity measurements
  - CTD_TEMPERATURE           # CTD temperature profiles
  - CTD_SALINITY             # CTD salinity profiles
  # - ALL_TEMPERATURE           # Includes ALL temperature types
  - SATELLITE_SSH             # Sea surface height from satellites

# Time window for matching observations to model output
time_window:
  days: 5      # Primary time window in days
  hours: 0     # Additional hours
  minutes: 0   # Additional minutes  
  seconds: 0   # Additional seconds
  weeks: 0     # Additional weeks (converted to days)
  months: 0    # Additional months (converted to days, ~30 days/month)
  years: 0     # Additional years (converted to days, ~365 days/year)