# ==========================================
# CrocoCamp Configuration Example
# ==========================================

####### INPUT FILES #######
# Directory containing model .nc files to process
model_files_folder: /glade/u/home/emilanese/work/DATA/CrocoCamp/demo/in_mom6/

# Model configuration files (must be .nc files)
template_file: /glade/u/home/emilanese/work/DATA/CrocoCamp/demo/in_mom6/NWA_demo_01.nc
static_file: /glade/u/home/emilanese/work/DATA/CrocoCamp/demo/in_mom6_ref/NWA-demo-static.nc
ocean_geometry:  /glade/u/home/emilanese/work/DATA/CrocoCamp/demo/in_mom6_ref/NWA-demo-ocean_geometry.nc

# Directory containing observation files
obs_seq_in_folder: /glade/u/home/emilanese/work/DATA/CrocoCamp/demo/in_WOD/

####### OUTPUT FILES #######
# Output directory for processed files (will be created if it doesn't exist)
output_folder: ./out_obs_seq_in/
input_nml_bck: ./input_bckp
trimmed_obs_folder: ./out_trimmed_obs_seq_in
parquet_folder: ./out_parquet/

####### DART #######
# Path to DART's perfect model obs executable
perfect_model_obs_dir: /path/to/DART/models/MOM6/work

# Observation types to assimilate (can include ALL_<FIELD> entries)
use_these_obs:
   - ALL_TEMPERATURE           # Includes ALL temperature types
#  - FLOAT_TEMPERATURE          # Argo float temperature measurements
#  - FLOAT_SALINITY            # Argo float salinity measurements

# Time window for matching observations to model output
time_window:
  days: 999      # Primary time window in days
  hours: 0     # Additional hours
  minutes: 0   # Additional minutes
  seconds: 0   # Additional seconds
  weeks: 0     # Additional weeks (converted to days)
  months: 0    # Additional months (converted to days, ~30 days/month)
  years: 0     # Additional years (converted to days, ~365 days/year)
